services:
  postgresql:
    image: 'postgres:latest'
    environment:
#      - POSTGRESQL_USERNAME=myuser
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=testdb
#      - PGDATA
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - cache:/data